[build]
  command = "npm run build"
  publish = "docs/.vitepress/dist"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "https://pangolin.netlify.app/*"
  to = "https://pangolinjs.org/:splat"
  force = true

[[redirects]]
  from = "https://v6.pangolinjs.org/*"
  to = "https://pangolinjs.org/v6/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://v5.pangolinjs.org/*"
  to = "https://pangolinjs.org/v5/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://v4.pangolinjs.org/*"
  to = "https://pangolinjs.org/v4/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://v3.pangolinjs.org/*"
  to = "https://pangolinjs.org/v3/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://v2.pangolinjs.org/*"
  to = "https://pangolinjs.org/v2/:splat"
  status = 302
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    permissions-policy = "interest-cohort=()"
