[build]
  environment = { NODE_VERSION = "16" }
  publish = ".vuepress/dist"
  command = "npm run build"

[[redirects]]
  from = "https://pangolin.netlify.com/*"
  to = "https://pangolinjs.org/:splat"
