[build]
  command = "npm run build"
  publish = "docs/.vitepress/dist"

[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "https://pangolin.netlify.app/*"
  to = "https://pangolinjs.org/:splat"
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    permissions-policy = "interest-cohort=()"
