name: Lint and Test
on: [push]

jobs:

  lint:
    name: Linting
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          version: 12
      - name: Install dependencies
        run: npm ci
      - name: Lint Markdown
        run: npm run lint
